version: '3.8'
services:
  labs:
    build: .
    container_name: labs
    depends_on:
      - db
    env_file:
      - .env
  db:
    container_name: labs_db
    build: ./db_setup
    environment:
      - MYSQL_ROOT_PASSWORD=${LABS_DB_PASSWORD}
      - DB_NAME=${LABS_DB_NAME}
    restart: always
    volumes:
      - ./mysql_vol:/var/lib/mysql
      - ./db_setup:/docker-entrypoint-initdb.d
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./proxy/data:/data
      - ./proxy/letsencrypt:/etc/letsencrypt

