version: '3.8'
services:
  labs_app:
    build: .
    container_name: labs
    entrypoint: ./entrypoint.sh
    depends_on:
      - mysql_labs
    environment:
      SECRET_KEY: ${SECRET_KEY}
      LABS_DB_NAME: ${LABS_DB_NAME}
      LABS_DB_USER: ${LABS_DB_USER}
      LABS_DB_PASSWORD: ${LABS_DB_PASSWORD}
      LABS_DB_HOST: mysql_labs
      LABS_DB_PORT: ${LABS_DB_PORT}
      USE_SQLITE: ${USE_SQLITE}
    ports:
      - "4000:4000"
  mysql_labs:
    container_name: mysql_labs
    build: ./docker_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=coffee
      - DB_NAME=labs
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker_mysql:/docker-entrypoint-initdb.d