# Generated by Django 4.2 on 2023-09-20 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labevent',
            name='topics',
            field=models.ManyToManyField(related_name='events', to='main.labtopic'),
        ),
        migrations.AddField(
            model_name='labevent',
            name='users',
            field=models.ManyToManyField(related_name='labs', to=settings.AUTH_USER_MODEL),
        ),
    ]
