# Generated by Django 4.2 on 2023-09-20 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_labevent_topics_labevent_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labevent',
            name='datetime',
        ),
        migrations.AddField(
            model_name='labevent',
            name='lab_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='labevent',
            name='close_login',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='labevent',
            name='close_logout',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
