# Generated by Django 4.2 on 2023-09-20 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_labevent_datetime_labevent_lab_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labevent',
            name='capacity',
            field=models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='labevent',
            name='close_login',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='labevent',
            name='close_logout',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='labevent',
            name='lab_datetime',
            field=models.DateTimeField(),
        ),
    ]
