# Generated by Django 4.2 on 2023-09-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_customuser_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
